version: '2.4'
volumes:
  uploads:
    external: true
services:
  image_converter:
    image: stasglebov/image-converter
    container_name: image_converter
    restart: unless-stopped
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./uploads:/uploads
  gateway:
    image: stasglebov/node-utils-gateway
    container_name: gateway
    restart: unless-stopped
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
    links:
      - rabbitmq
    ports:
      - 3090:3090
    depends_on:
      - rabbitmq
    volumes:
      - ./uploads:/uploads
  rabbitmq:
    image: 'rabbitmq:3.6.6-management'
    container_name: rabbit
    ports:
      - "4369:4369"
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
      - "35197:35197"
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./data/logs:/var/log/rabbitmq
    hostname: rabbit
